PACKAGE_NAME="cix-vpu-driver"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="amvx"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/updates"
CLEAN="make clean"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build"
